#==============================================================================#
#---------     Options for Steps in Targeted Probe Design Pipeline     --------#
#==============================================================================#

[general]
  final_probe_amount = '20'
  final_probe_random = true
  prokka_prediction_suffix = '.ffn'
  genome_bins_suffix = '.fasta'

[gc_percent]
  min_percent = '45'
  max_percent = '65'

[catch]
  probe_length = '40'
  probe_stride = '20'
  reuse_existing_probe_files = false

[paths]
  # Where are your source data files? Where do you want the resulting files located?
  working_dir = 'pipeline_results' # working_dir: 'This is the place to work on files... (default "pipeline_results")'
  genome_bins = 'cluster_genome_bins'
  prokka_dir  = 'cluster_prokka_annotations' # files in this dir used for creating new blastdbs
  use_blastdb = '' # can be "any_preexisting_db_path" or empty if new blastdbs to be created.

[blastn]
  evalue = '0.001'
  dust = 'no'
  num_alignments = '250' # Integer >1. (blastn default: 250)
  num_threads    = '2'   # how many cpus?

  # pre-defined fields = [ 'qseqid', 'sseqid', 'pident', 'length', 'qseq' ]
  # The above fields are used in probe filtering and evaluating.
  # Here you can a list of others to add, e.g.:
  # fields = ['mismatch', 'gapopen', 'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore']

[filters]
  musicc_list = [
    'asd', 'metK', 'pgk', 'adk', 'eno', 'tpiA', 'tyrS', 'trpS',
    'thrS', 'leuS', 'ileS', 'alaS', 'valS', 'metG', 'serS',
    'aspS', 'proS', 'cysS', 'argS', 'pheS', 'pheT', 'hisS',
    'pyrG', 'tsf', 'infB', 'ksgA', 'nusA', 'nusG', 'prfA',
    'frr', 'rpoA', 'secY', 'ffh', 'ftsY', 'mraW', 'rnhB',
    'smpB', 'grpE', 'uvrB', 'ychF', 'pyrH', 'nth', 'rsmH',
    'tRNA.ligase'
  ]
  trna_list = [
    '50S', '5S', '16S', '30S', '23S', 'repeat', 'tRNA-Ala', 'tRNA-Arg',
    'tRNA-Asn', 'tRNA-Asp', 'tRNA-Cys', 'tRNA-Glu', 'tRNA-Gln',
    'tRNA-Gly', 'tRNA-His', 'tRNA-Ile', 'tRNA-Leu', 'tRNA-Lys',
    'tRNA-Met', 'tRNA-Phe', 'tRNA-Pro', 'tRNA-Ser', 'tRNA-Thr',
    'tRNA-Trp', 'tRNA-Tyr', 'tRNA-val', 'hypothetical'
  ]

[APPS]
  # Use only the main executable name if they are in your $PATH !
  # e.g. load the required 'module's before running this pipeline.
  catch = 'catch_design.py'
  blastdb = 'makeblastdb'
  blastn = 'blastn'

